### ISSUE TITLE
Imperium - Gestures Don't Work With MitsuhaXI

### ISSUE THREAD

**Issue by Kosezu** [LacertosusRepo/LacertosusRepo.github.io#10]
## *For the title, follow this example: Tweak - Short Bug Description*

------------------
**Tweak/Theme: Imperium and MitsuhaXI**
**Version: 2.0 and 0.5.3 respectively**
**Device: iPhone 6S**
**iOS Version: 11.3.1**

-----------------
**Issue/Bug:**

The gestures for Imperium do not work when Mitsuha's visualizer is present.
-------------------------
**Additional Comments:**

Works when visualizer is not present. Thank you for this tweak, it's awesome!

**Comment by LacertosusRepo** [comment]
Thanks for reporting!I have both installed with no issues, do you have any other CC tweaks installed?

**Comment by Kosezu** [comment]
I do, but I disabled just Mitsuha and it worked fine just doing that. I only did that once though.

Other tweaks that might affect it:

Artsy
BetterCCXI
CCLinker
CCMusicArtwork
CCSupport (with a few additional toggles)
colormycc
NoctisXI
PowerSelector
RealCC
SugarCane

I know that's quite a list.

**Comment by LacertosusRepo** [comment]
None of those broke it for me, very puzzling.

**Comment by Kosezu** [comment]
It seems to work when I reset all settings, but once I make a change from the default, it stops working.

**Comment by LacertosusRepo** [comment]
Cannot replicate the bug, not sure what causing it. Open another if the error continues/report back if the cause is found.
