### ISSUE TITLE
Stellae 1.0- iPhone 5s iOS11.2.1-whenever setting wallpaper, manually or by the time setting, it puts me in safe mode

### ISSUE THREAD

**Issue by l8rgt** [LacertosusRepo/LacertosusRepo.github.io#12]
# Bug Report

### iOS Version:

-----------------
**Issue/Bug:**

-------------------------
**Additional Comments:**

**Comment by LacertosusRepo** [comment]
Fixed as of version 1.1. Should be available on Packix soon.
