### ISSUE TITLE
Stellae doesn't work. Version 1.1

### ISSUE THREAD

**Issue by jeppes1995** [LacertosusRepo/LacertosusRepo.github.io#14]
# Bug Report

### Tweak/Theme:
Stellae

### Version:
1.1

### Device:
iPhone X

### iOS Version:
12.1.2

-----------------
**Issue/Bug:**
For me it doesn't save any of my settings. Clock keeps reseting, it doesn't save the new subreddit I put in, and none of the buttons work in settings (respring, change now, save wallpaper).
I'm on 1.1, iPhone X iOS 12.1.2

**Comment by LacertosusRepo** [comment]
Thanks for the report, other users are reporting the same issue.
