### ISSUE TITLE
Stellae - Remove Activator as a dependency

### ISSUE THREAD

**Issue by MCJack123** [LacertosusRepo/LacertosusRepo.github.io#16]
# Bug Report
Stellae - Remove Activator as a dependency
### Tweak/Theme:

Stellae
### Version:

1.2
### Device:

iPhone 7 Plus
### iOS Version:

12.1

-----------------
**Issue/Bug:**

Activator causes SpringBoard on my device to crash. I cannot have Activator installed, but Stellae now requires Activator as a dependency even though it only is used for actions. (Activator is version 1.9.12.)

-------------------------
**Additional Comments:**

**Comment by LacertosusRepo** [comment]
I have migrated over to Activator instead of using a awful hacked-together time checking method. Activator is now *nearly* required for this tweak to work. Try updating Activator to v1.9.13~beta4 from https://rpetri.ch/repo/
