### ISSUE TITLE
Speculum: Time doesn’t update every second

### ISSUE THREAD

**Issue by akifwnd** [LacertosusRepo/LacertosusRepo.github.io#18]
## *For the title, follow this example: Tweak - Short Bug Description*

------------------
**Tweak/Theme:** Speculum
**Version:** 1.3.3 (Happens on all versions)
**Device:** iPhone XS
**iOS Version:** 12.1

-----------------
**Issue/Bug:**  clock does not update every second on the home screen so adding as to the time format essentially makes it useless.

-------------------------
**Additional Comments:**

**Comment by Tizioincognit0** [comment]
But on iOS 11 with the tweak [FastForwardTime](https://github.com/Kaitouiet/FastForwardTime) - which is incompatible with iOS 12 - the time updated every second.

**Comment by akifwnd** [comment]
To add to Tizioincognit0’s comment, the NiceBarX tweak also has an option to update status bar time every second if you decide to add ss to the time format. I assume the status bar time is handled the same way as the lock screen time.

**Comment by Tizioincognit0** [comment]
> To add to Tizioincognit0’s comment, the NiceBarX tweak also has an option to update status bar time every second if you decide to add ss to the time format. I assume the status bar time is handled the same way as the lock screen time.

Also the tweak “Cloaky” has the same option and it works fine on iOS 12.2.
![photo_2019-07-18 12 27 25](https://user-images.githubusercontent.com/40031873/61454111-3f920700-a960-11e9-89bb-ad1162766a35.jpeg)

**Comment by LacertosusRepo** [comment]
To keep the time and date as accurate as possible, I use the one provided by Apple that usually is used for the clock. They only update this date every minute, so seconds will not work.

**Comment by Tizioincognit0** [comment]
But also NiceBarX and Cloaky are accurate as possible even if they don’t use the one provided by Apple.

**Comment by Tizioincognit0** [comment]
But also NiceBarX and Cloaky are accurate as possible even if they don’t use the one provided by Apple.

**Comment by Tizioincognit0** [comment]
Now also the open source tweak FastForwardTime refreshes seconds on iOS 12.x. You can find its source code [here](https://github.com/Kaitouiet/FastForwardTime).

**Comment by turtlemaster19** [comment]
@LacertosusRepo Please reconsider this decision, or make it a setting for those of us that want to proceed with updating seconds despite the risks.
