### ISSUE TITLE
[BUG] Libellum - sizeToMimic crash

### ISSUE THREAD

**Issue by jawsoftware** [LacertosusRepo/LacertosusRepo.github.io#22]
#### **Information:**
- *iPhone 6s*
- *iOS 12.1.2, unc0ver jb*
- *Libellum*
- *1.0*

#### **Describe the bug:**
Resprings (substrate crash) with varous apps

#### **To Reproduce:**
Random resprings

#### **Cr4shed info**
Process: SpringBoard
Bundle id: com.apple.springboard
Exception type: NSInvalidArgumentException
Reason: -[LibellumView setSizeToMimic:]: unrecognized selector sent to instance 0x15dd11530
Culprit: Unknown
Device: iPhone 6s, iOS 12.1.2

**Comment by LacertosusRepo** [comment]
Fixed
