### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by sabdemo** [LacertosusRepo/LacertosusRepo.github.io#25]
#### **Information:**
- iPhone SE
- 13.2.2
- Libellum
- 1.0~B3

1. When iPhone is in album mode and I open a notification center, my iPhone resprings. It happens not every time, but the most of the time. Especially after long time iPhone wasn't used. 

I haven't seen this problem on beta 2 version. 

2. When I try to open settings - they crashed all the time. It was both on the 2nd and 3rd beta.

For me the most important is to solve the first problem. So if you could post the 2nd beta back to cydia, or to send a deb file - it would be nice. But I also would be very glad, if you could update the tweak, so to solve both problems on iOS 13.

**Comment by LacertosusRepo** [comment]
For issue 2, you need to install libpackageinfo (SparkDev) https://twitter.com/LacertosusDeus/status/1199932693275799552

**Comment by LacertosusRepo** [comment]
Libellum 1.0~b4 fixes crashes.
