### ISSUE TITLE
Volume Lock

### ISSUE THREAD

**Issue by Dbloxia** [LacertosusRepo/LacertosusRepo.github.io#27]
When I try to decompile Volume Lock, it says unknown near 'UiPressesEvent' and 'UiPress'

**Comment by LacertosusRepo** [comment]
Might be because you're using a different SDK that doesnt have UIPressesEvent and UIPress declared. Just add this to the top of your tweak.x:

```
@interface UIPressesEvent : UIEvent
@property (nonatomic, readonly) NSSet *allPresses;
@end`

@interface UIPress : NSObject
@property (assign, nonatomic) long long type;
@property (assign, nonatomic) double force;
@end
```

To add this isn't an issue or request for this tweak, next time send me an email or message me on reddit or twitter.

**Comment by Simulation-jb** [comment]
Can I get the sdk this was in?

**Comment by LacertosusRepo** [comment]
@Simulation-jb this was compiled using the iOS [11.2 patched SDK from theos](https://github.com/theos/sdks).

**Comment by Simulation-jb** [comment]
Ah thanks

**Comment by Simulation-jb** [comment]
Unrelated thing, i was trying to add a alert view, how can I fix this? 
  "_OBJC_CLASS_$_UIAlertView", referenced from:

**Comment by LacertosusRepo** [comment]
@Simulation-jb this is not the place for general help. Contact me by [email](mailto:LacertosusThemes@gmail.com), [reddit](https://reddit.com/user/Bezerk_Jesus/), or [twitter](https://twitter.com/LacertosusDeus) for help or ask [r/JailbreakDevelopers](https://old.reddit.com/r/jailbreakdevelopers/).

**Comment by LacertosusRepo** [comment]
[Messaged me on Reddit](https://imgur.com/a/agbk9ia)
