### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by laithayoub71** [LacertosusRepo/LacertosusRepo.github.io#29]
#### **Information:**
- *Device:* iPhone XR
- *iOS:* 12.4
- *Tweak:* Libellum
- *Package Version:* 1.1

#### **Describe the bug:**
Probably just an A12 bug but every time Libellum’s preference bundle is clicked on in the Settings, it hangs for a couple of seconds then crashes the Settings app. Upon relaunching, all preference bundles of all installed tweaks are gone. A relaunch of the Settings app fixes this but upon clicking on Libellum, it crashes again. It’s a cycle of crashes.

#### **To Reproduce:**
1. Open the Settings app
2. Click on the Libellum preference bundle
3. Settings app crashes

#### **Expected behavior:**
The preference bundle for Libellum should load.

#### **Screenshots:**
https://m.imgur.com/HNG6xux

#### **Additional context**
Crash Log: https://pastebin.com/PuLtfWkz

**Comment by LacertosusRepo** [comment]
I believe I know the issue and will push and update later tonight.

**Comment by LacertosusRepo** [comment]
Let me know if update v1.1-1 foxes the crash.

**Comment by laithayoub71** [comment]
Just installed the latest version and it worked perfectly! Thank you for
taking the time and thank you for a very quick response. And more
importantly, thanks for making this project open source. Underrated
developer! Libellum is great man it helps me keep in track!! Well done.
