### ISSUE TITLE
[REQUEST] Libellum

### ISSUE THREAD

**Issue by almed1** [LacertosusRepo/LacertosusRepo.github.io#32]
Hi 
How are doing today?
Could you please make libellum compatible with the tweak (lockwidget)
https://repo.dynastic.co/package/lockwidgets
In this link the developer show how to make widgets compatible with (lockwidgets) https://github.com/ConorTheDev/LockWidgets/wiki

**Comment by LacertosusRepo** [comment]
LockWidgets seemingly works fine with Libellum.
