### ISSUE TITLE
[BUG] Speculum: Unable to change color

### ISSUE THREAD

**Issue by iancbogue** [LacertosusRepo/LacertosusRepo.github.io#33]
#### **Information:**
- *Device:* iPhone 8 Plus
- *iOS:* 13.3.1
- *Tweak:* Speculum
- *Package Version:* 1.3.5

#### **Describe the bug:**
I am unable to change colors of different clock elements. Clicking on “Font Color” does nothing. No separate page is opened with a color picker. Speculum is still able to set the color from the current wallpaper, however, but once changed I cannot change it back.
#### **To Reproduce:**
Open Settings and navigate to the section for Speculum. Open any of the three Label Settings buttons and tap on “Change Font”. Nothing happens.

#### **Expected behavior:**
A page or pop up (I can’t remember what it used to do) should open which includes a color picker

#### **Additional context**
I am using libcolorpicker-nepeta. Trying regular libcolorpicker from BigBoss uninstalled a bunch of my tweaks.

**Comment by LacertosusRepo** [comment]
Speculum does not fully support iOS 13.
