### ISSUE TITLE
[BUG] Speculum

### ISSUE THREAD

**Issue by lawrencecoding** [LacertosusRepo/LacertosusRepo.github.io#35]
#### **Information:**
- *Device:iPhone X
- *iOS: 13.5
- *Tweak: Speculum
- *Package Version: 1.3.5

#### **Describe the bug:**
When in landscape mode, such as when watching a YouTube video, the location of the widget when opening the Notification Center should be on the left side instead of on the right, on top of the rest of the items. Bug is mostly noticeable in combination with Complications tweak since they both get on top of each other. Even if not considered a bug, there could be an option to have different locations as there already is in the settings for either left, right, or Center, but different setting for landscape and portrait.

#### **To Reproduce:**
Open any YouTube video in landscape mode, and with having complications installed, time stays on top of complications on the right side instead of on the left.

#### **Expected behavior:**
Expect to either have the time on the left by default when in landscape or to have the option to have different location dependent on orientation.

#### **Screenshots:**
![C18A50C0-BF65-4BFC-82F9-7D86925509F5](https://user-images.githubusercontent.com/51058594/82906330-ff76ba00-9f5c-11ea-9e20-861c597d04f0.png)

**Comment by LacertosusRepo** [comment]
Speculum does not fully support iOS 13 and I unfortunately have no intention of updating it currently.
