### ISSUE TITLE
[BUG] VolumeLock

### ISSUE THREAD

**Issue by wahidulislamriyad** [LacertosusRepo/LacertosusRepo.github.io#37]
**Information:**
- Device: iPhone 7
- iOS: 12.1.2
- Tweak: VolumeLock
- Package Version: 1.2

**Describe the bug:**
Gesture (Volume buttons both press) for the tweak doesn’t work with Activator installed latest version. Cause, Activator took over both volume buttons to it’s own action. Therefore, it would be great if the tweak is made as an extension for Activator. Or add other gestures for the tweak.

**To Reproduce:**
Install Activator latest version, an then VolumeLock won’t anymore.

**Expected behavior:**
Expecting to have the tweak as extension for Activator or add more gestures for the tweak.

**Comment by LacertosusRepo** [comment]
Cannot replicate this behavior, VolumeLock and Activator seemingly work side by side for me after testing. It might be an iOS 12 issue only, but without a device on iOS 12 I cannot be sure.
