### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by JohnLockeNJ** [LacertosusRepo/LacertosusRepo.github.io#38]
#### **Information:**
- *Device:* iPhone 8
- *iOS:* 13.5
- *Tweak:* Libellum
- *Package Version:* 1.4

#### **Describe the bug:**
I installed Libellum 1.4 and resprung just fine, but when later I rebooted and tried to jailbreak again with Unc0ver it would not boot. No problems with Libellum 1.3-1.

#### **To Reproduce:**
If possible, describe how to reproduce the error.
Trying to jailbreak with Unc0ver set to load tweaks with Libellum 1.4 installed.

#### **Expected behavior:**
I expected to jailbreak just fine with Libellum 1.4.
#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

My fix was to use SnapBack to downgrade to Libellum 1.3-1.  Maybe you could enable people to downgrade in Cydia until the bug is fixed? Cydia wouldn’t let me downgrade which is why I had to use SnapBack.

**Comment by LacertosusRepo** [comment]
I've been getting reports of issues with booting with my tweaks installed, yet I can boot with them just fine on using Unc0ver.

**Comment by LacertosusRepo** [comment]
There is now a temporary fix with v1.4.3, thought the underlying issue is still unknown.

**Comment by JohnLockeNJ** [comment]
I installed 1.4.4 and it's working great! No issues rebooting when I re-jailbreak with Unc0ver.
