### ISSUE TITLE
[BUG] ColoredScrollIndicator

### ISSUE THREAD

**Issue by dylan27911** [LacertosusRepo/LacertosusRepo.github.io#39]
#### **Information:**
- *Device:* iphone xs max
- *iOS:* 13.5
- *Tweak:* color scroller
- *Package Version:*latest version

#### **Describe the bug:**
A clear and concise description of what the bug is. When your phone dies and you go to rejailbreak you get stuck on the apple logo with this tweak but if you delete it cydia will load back up.

#### **To Reproduce:**
If possible, describe how to reproduce the error.
I had to delete the tweak for cydia to rejailbreak
#### **Expected behavior:**
A clear and concise description of what you expected to happen. I expected after I removed the tweak it would rejailbreak with no problems

#### **Screenshots:**
If applicable, add screenshots to help explain your problem. No screenshots just stuck on apple logo had to remove

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste. Please fix! I love this tweak!

**Comment by LacertosusRepo** [comment]
This should be solved, forgot to close this issue after pushing the update long ago.
