### ISSUE TITLE
Left is Right or Right is Left?

### ISSUE THREAD

**Issue by Cheesybiscuit** [LacertosusRepo/LacertosusRepo.github.io#4]
------------------
**Tweak/Theme:** Imperium
**Version:** 1.3
**Device:**  iPhone10,3
**iOS Version:** 11.3.1

-----------------
**Issue/Bug:**
If I swipe to the right, it will perform the “left” action.

-------------------------
**Additional Comments:**
No present in previous versions.

Update:
Please close issue

After reassigning the values for each, they work correctly. It was only leaving the values untouched after updating that caused the issue.

**Comment by LacertosusRepo** [comment]
Thanks for reporting, glad you were able to fix it.
