### ISSUE TITLE
[BUG] improvify 

### ISSUE THREAD

**Issue by eglacias** [LacertosusRepo/LacertosusRepo.github.io#40]
iPhone 6s Plus, iOS 12.4.1, improvify latest version, by URI I assume you mean the share link that you can get in the playlist. I added one of those for the favorite

Also There is no new button added in now playing list.  It seems that it is not modifying Spotify whatsoever, except until I added a URI it would immediately crash with tapping on the playlist 

#### **Information:**
- *Device:*
- *iOS:*
- *Tweak:*
- *Package Version:*

#### **To Reproduce:**
If possible, describe how to reproduce the error.

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by eglacias** [comment]
I guess I’ll mention that today’s June 1 version of Spotify is the first I’ve seen that adds a huge green button to the right just start playing the playlist  in a huge button to the left  to remove downloads

**Comment by LacertosusRepo** [comment]
This tweak is no longer being updated due to the difficulty of maintaining updates with Spotify.
