### ISSUE TITLE
[BUG] Speculum

### ISSUE THREAD

**Issue by fallengravity** [LacertosusRepo/LacertosusRepo.github.io#41]
#### **Information:**
- *Device: iPhone X - 64 GBs*
- *iOS: 13.5*
- *Tweak: Speculum
- *Package Version: 1.3.5*

#### **Describe the bug:**
This seems to happen frequently, the time are weather get stuck on the lock screen and Notification Center.  Meaning the time & weather do not change/update which means the time is always wrong

#### **Screenshots:**
First is the lock screen time: 

![4A177289-ED0D-4F92-B64D-DEB87CBDAFF9](https://user-images.githubusercontent.com/37632291/83868402-19698700-a72b-11ea-944d-cf72d778df22.jpeg)

This is the time after unlocking my phone:

![716ABCC6-1FB7-47CD-A937-C7F3AF2D6395](https://user-images.githubusercontent.com/37632291/83868453-2be3c080-a72b-11ea-84ac-f8db2fbf58c4.jpeg)

**Comment by LacertosusRepo** [comment]
Speculum doesn't support iOS 13 if you look at the compatibility on Packix.
