### ISSUE TITLE
[BUG] Libellum Preference Bundle Issue

### ISSUE THREAD

**Issue by laithayoub71** [LacertosusRepo/LacertosusRepo.github.io#43]
#### **Information:**
- *Device:* iPhone XR
- *iOS:* 13.5
- *Tweak:* Libellum
- *Package Version:* 1.4.8 (Latest)

#### **Describe the bug:**
The tweak now shows a preference bundle error in the settings. It did not do this previously.

#### **To Reproduce:**
1. Open Settings app
2. Scroll down and click on the “Libellum” tweak

#### **Expected behavior:**
The tweak should show its settings when clicked on

#### **Screenshots:**
![D291EE4E-F466-4EA5-A930-5BF3099D5CF6](https://user-images.githubusercontent.com/50788891/91629032-78354a00-e982-11ea-9d55-43e28e4c3cd8.png)

#### **Additional context**
This error did not show up previously. I have the latest version of rocket bootstrap and cephei installed.

**Comment by LacertosusRepo** [comment]
Make sure you have Alderis installed, though I've listed it as a dependency it doesn't seem to install itself.

**Comment by laithayoub71** [comment]
Hahah well that was a very quick fix. It sure worked thank you so much!
