### ISSUE TITLE
[BUG] Dock Indicators

### ISSUE THREAD

**Issue by robertybob** [LacertosusRepo/LacertosusRepo.github.io#44]
#### **Information:**
- *Device:* XS
- *iOS:* 13.5
- *Tweak:* Dock Indicators
- *Package Version:* 1.0.1

#### **Describe the bug:**
Unusable as it makes Springboard crash

#### **To Reproduce:**
Installed tweak, restarted Springboard, opening any app crashes it 

#### **Expected behavior:**
The tweak working

#### **Screenshots:**
![49D43513-3152-48C8-8FB7-C6C34456C1B4](https://user-images.githubusercontent.com/2610395/95693864-9602f980-0c26-11eb-97a1-58a94d39d69c.png)

#### **Additional context**
[Crash log](https://www.dropbox.com/s/bzrtp8v9vv4wp74/File%2012-10-2020%2C%2001%2008%2003.txt?dl=0)

**Comment by LacertosusRepo** [comment]
Can you send a screenshot or describe what apps are in your dock? Any specific dock tweaks?

**Comment by robertybob** [comment]
Dock tweaks - I have Harbor 3 and Rofi (not sure if this one counts as a dock tweak to be honest)

**Comment by robertybob** [comment]
![Uploading 38B79376-D791-4619-80A3-86F29D80C5C2.png…]()

**Comment by robertybob** [comment]
![1713CB92-B884-4109-ACE6-74214E945248](https://user-images.githubusercontent.com/2610395/95694722-66a2bb80-0c2b-11eb-9679-bf0cab2193a3.png)

**Comment by LacertosusRepo** [comment]
Fixed! Will be working in v1.0.2
