### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by CySxL** [LacertosusRepo/LacertosusRepo.github.io#46]
#### **Information:**
- *Device:* iPhoneX
- *iOS:* iOS13.3
- *Tweak:* Libellum
- *Package Version:* 1.5.1
 
#### **Describe the bug:**

In stock light mode, respring once and the tint of texts in adaptive mode would turn to white.   

#### **To Reproduce:**
If possible, describe how to reproduce the error.

In stock light mode and respring.

#### **Expected behavior:**

Tint of text should be black in light mode.

Though a quick toggling of light/dark mode again would be this issue. 

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by CySxL** [comment]
Screenshot here
![Uploading 6B8B375A-54B5-48D5-A421-5AA8C0CC1AB0.png…]()

**Comment by CySxL** [comment]
![B1E00B59-B28A-4195-8E5D-B53CE3BE1711](https://user-images.githubusercontent.com/15531137/95822521-aa4a1200-0d5e-11eb-9499-8026eab01eb1.png)

**Comment by LacertosusRepo** [comment]
Fixed for the next update.
