### ISSUE TITLE
Imperium - CC can’t scroll

### ISSUE THREAD

**Issue by jiajianng** [LacertosusRepo/LacertosusRepo.github.io#5]
**Tweak/Theme:** Imperium
**Version:** 1.4
**Device:** iPhone 8
**iOS Version:** 11.4b3

-----------------
**Issue/Bug:**
after updating, the Control Center is unable to scroll if you have many modules like I do which enables scrolling. 

-------------------------
**Additional Comments:**

**Comment by LacertosusRepo** [comment]
Thanks for reporting! Will look into it.

**Comment by LacertosusRepo** [comment]
Ive looked into this and so far, I have no issues scrolling. Maybe its a conflicting tweak?
