### ISSUE TITLE
[REQUEST] Dock Indicators

### ISSUE THREAD

**Issue by DP3rS** [LacertosusRepo/LacertosusRepo.github.io#50]
#### **Is your feature request related to a problem? Please describe.**
With the addition of Dock Indicators, I find that I’m bringing up the quick action menu a lot more on open apps, thinking that I’d be able to close them, like I would on a Mac.

#### **Describe the solution you'd like**
Similarly to how you can right click an app on macOS and close it, there could be a quick action, only on open apps, that allows them to be closed. This would be particularly useful on iPads as they have the ability to support a touchpad/mouse where an app can be right-clicked to bring up the quick action menu. Whether this is integrated into Dock Indicators or made it into a separate tweak, it’s fine either way. It just seems that this functionality would compliment Dock Indicators really well.

#### **Describe alternatives you've considered**
After a lot of searching, no existing tweaks appear to provide this functionality.

#### **Additional context**
For reference, here is what a quick action menu looks like:
![IMG_0484](https://user-images.githubusercontent.com/26558731/98566476-cb7a2180-227c-11eb-8193-7748a38064bd.jpeg)

Thanks for taking the time to read this.

**Comment by JoelPeterPage** [comment]
I have issues with DockIndicators always indicating messages until I respring, contact if you want more information about the tweaks that might be messing things up! 

I use FloatingDock13 and a few messages tweaks

**Comment by LacertosusRepo** [comment]
@JoelPeterPage Make a new issue here: https://github.com/LacertosusRepo/LacertosusRepo.github.io/issues/new/choose

**Comment by JoelPeterPage** [comment]
I’ve issued properly now..

Contact if you need more information.

Kind regards,
Joel Page
Sent from my iPhone


On 29 Nov 2020, at 15:49, LacertosusDeus <notifications@github.com> wrote:

﻿

@JoelPeterPage<https://github.com/JoelPeterPage> Make a new issue here: https://github.com/LacertosusRepo/LacertosusRepo.github.io/issues/new/choose
