### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by hyper01001** [LacertosusRepo/LacertosusRepo.github.io#51]
#### **Information:**
- *Device:* Iphone 6s
- *iOS:* 12.1.2
- *Tweak:* Libellum 
- *Package Version:* 1.5.2 and 1.5.3

#### **Describe the bug:**
I installed Libellum and the colorpicker package that comes along with the tweak but whenever i go to Libellum's section in settings, it says "There was an error loading the preference bundle for Libellum: The bundle "LibellumPrefs.bundle" couldn't be loaded because it is damaged or missing necessary resources." 
Then i reinstalled it several times and also check it everytime but it returns the same problem (i also reinstalled the colorpicker along with the tweak) 

#### **To Reproduce:**
If possible, describe how to reproduce the error.

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by LacertosusRepo** [comment]
I attached some older versions of libellum (v1.4.1 and v1.4.8). If you could test them and check if the preference bundle loads, it could help me determine if there was a change to the preferences I made causing this.

[Older Libellum Versionszip.zip](https://github.com/LacertosusRepo/LacertosusRepo.github.io/files/5598672/Older.Libellum.Versionszip.zip)

**Comment by LacertosusRepo** [comment]
Only other suggestion is to delete the preferences file at **/User/Library/Preferences/com.lacertosusrepo.libellum**. Closing since no response.
