### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by rtayob** [LacertosusRepo/LacertosusRepo.github.io#53]
#### **Information:**
- *Device:* iphone 12 mini
- *iOS:* 14.2
- *Tweak:* libellum 
- *Package Version:* 1.5.3

#### **Describe the bug:**
Puts the phone I safe mode as soon as I respiring after Install. 

#### **To Reproduce:**
Install on with zebra or Cydia. On 14.2 it just reboots into safe mode 

#### **Expected behavior:**
Not safe mode 

#### **Additional context**
Not sure what could be the problem. Maybe 14.2 on unc0ver.  I even did a rootfs and only installed libellum to see if any conflicts. Nothing. Same problem.

**Comment by LacertosusRepo** [comment]
Without a crashlog, it is unlikely that I will be able to guess what is causing the issue.

**Comment by rtayob** [comment]
Not showing any logs in Cr4shed 

![6F96B1FC-D967-4ACC-A7A7-5C79B3BBC463](https://user-images.githubusercontent.com/72606050/109745376-702dbf80-7bdc-11eb-963a-e45e4313ce19.png)
![6DE4F64C-9008-4E17-9F3F-BB52F62DEEB0](https://user-images.githubusercontent.com/72606050/109745388-76bc3700-7bdc-11eb-8085-fc57f4602653.png)

**Comment by rtayob** [comment]
![DDD64E81-0D83-4627-9198-E321F3CED630](https://user-images.githubusercontent.com/72606050/109746293-d6671200-7bdd-11eb-8cb0-f09bdec56b35.png)

**Comment by rtayob** [comment]
CrashReporter working.m now. How do I email the log to you ?

**Comment by rtayob** [comment]
Issue seems to be with the colour picker dependency and the new unc0ver. I downgraded it and libellum works. I can’t change colours but at least the tweak works for now.

**Comment by LacertosusRepo** [comment]
Yep caused by Alderis it seems. Email me the log to me LacertosusThemes@gmail.com.
