### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by laithayoub71** [LacertosusRepo/LacertosusRepo.github.io#54]
#### **Information:**
- *Device:* iPhone 11 Pro Max
- *iOS:* 14.3
- *Tweak:* Libellum
- *Package Version:* 1.5.3

#### **Describe the bug:**
Puts device in safe mode

#### **To Reproduce:**
1. Open Cydia
2. Search "Libellum"
3. Click "Install"
4. Click "Restart SpringBoard" after tweak is downloaded and installed
5. Device enters safe mode, forcing me to uninstall the tweak

#### **Expected behavior:**
Libellum should load/device should not be in recovery mode

#### **Screenshots:**
Safe Mode

#### **Additional context**
None. I think the tweak just isn't compatible with iOS 14

**Comment by LacertosusRepo** [comment]
This is an issue with Alderis on arm64e devices.
