### ISSUE TITLE
[REQUEST] Libellum

### ISSUE THREAD

**Issue by enaloha** [LacertosusRepo/LacertosusRepo.github.io#55]
#### **Is your feature request related to a problem? Please describe.**
I like the concept a lot, but I also like to have a clean lockscreen when I don't have a note, so...

#### **Describe the solution you'd like**
If I don't have a note at all, there is no point in showing a blank rectangle (even a small one). So just hide it. If I want to add a note (the first one), let me double-tap on lock screen and reveal the note rectangle for text input. 

So if I have notes, but still want to hide them, provide two options in the top left and right corners of the note: a close icon (x) to close the notes and again reveal them by double-tap or a minimize icon (-) to leave a small icon on the lockscreen (e.g., a textfile icon, maybe with the number of notes in it) so that one keeps a reminder of existing notes on the lockscreen without the full note visible at all times.

#### **Describe alternatives you've considered**
N/A

#### **Additional context**
Nope, this tweak is next to perfect. Thanks for making it. It's a brilliant idea.

**Comment by LacertosusRepo** [comment]
A form of the first solution will appear in the next update.

**Comment by LacertosusRepo** [comment]
The minimizing like feature you described will not though.
