### ISSUE TITLE
[BUG] Libellum 1.6.1 Does Work on iOS 13.7 running checkra1n

### ISSUE THREAD

**Issue by eshack94** [LacertosusRepo/LacertosusRepo.github.io#57]
#### **Information:**
- *Device:* iPhone X
- *iOS:* 13.7 (jailbroken with checkra1n)
- *Tweak:* Libellum
- *Package Version:* 1.6.1

#### **Describe the bug:**
Libellum does not appear on the lockscreen after upgrading from Libellum `1.6.0` to version `1.6.1` on jailbroken iPhone X matching the description in the Information section above.

#### **To Reproduce:**
Install Libellum `1.6.0` on a jailbroken device matching info in first section. Then upgrade to version `1.6.1`.

#### **Expected behavior:**
Libellum continues to work as expected on the upgraded version.

#### **Screenshots:**
Not needed.

#### **Additional context**
No crashes associated. The tweak just isn't working when I upgrade to version 1.6.1. I wish I could provide more info, but there are no associated error messages or debug logs that I could see.

Thanks for your hard work on this! I think this tweak is an excellent concept and I enjoy using it.

**Comment by LacertosusRepo** [comment]
Libellum 1.6.2 fixes this issue.
