### ISSUE TITLE
[BUG] LIBELLUM

### ISSUE THREAD

**Issue by kotatrader** [LacertosusRepo/LacertosusRepo.github.io#59]
#### **Information:**
- *Device:* Iphone 11 Pro Max
- *iOS:* 14.2
- *Tweak:* Libellum
- *Package Version:* Last

#### **Describe the bug:**
iOS crashes on respring, after installing the tweak

#### **Additional context**
Date: 16/03/2021, 12:29
Process: SpringBoard
Bundle id: com.apple.springboard
Device: iPhone 11 Pro Max, iOS 14.2
Bundle version: 1.0

Exception type: NSInvalidArgumentException
Reason: -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x8b597348bc42f1c3
Culprit: Libellum.dylib

**Comment by LacertosusRepo** [comment]
Would you be able to provide the full crash log, along with the preferences file?

You can find the preferences file at **/User/Library/Preferences/** named **com.lacertosusrepo.libellumprefs**.

**Comment by kotatrader** [comment]
[text-29BE655F260D-1.txt](https://github.com/LacertosusRepo/LacertosusRepo.github.io/files/6175808/text-29BE655F260D-1.txt)

[com.lacertosusrepo.libellumprefs.plist.zip](https://github.com/LacertosusRepo/LacertosusRepo.github.io/files/6175816/com.lacertosusrepo.libellumprefs.plist.zip)

Both files attached

Thank you

**Comment by LacertosusRepo** [comment]
I see the issue. If you want to start using Libellum now, delete that preference file from it's location. Ill add a fix to prevent this crash from occurring.

**Comment by kotatrader** [comment]
Done. It’s working now! Thanks, you’re the best!!!
