### ISSUE TITLE
Imperium not working after installing xeninfo 

### ISSUE THREAD

**Issue by Dtwpurple** [LacertosusRepo/LacertosusRepo.github.io#6]
## *For the title, follow this example: Tweak - Short Bug Description*

------------------
**Tweak/Theme:**
**Version:**
**Device:**
**iOS Version:**

-----------------
**Issue/Bug:**

-------------------------
**Additional Comments:**

**Comment by LacertosusRepo** [comment]
Thanks for reporting! Will look into it.

**Comment by LacertosusRepo** [comment]
I've tested with XenInfo and had no issues, try going into Imperium settings and re-selecting settings.

**Comment by Dtwpurple** [comment]
i downgraded to 1.3 and it works just fine. Ill try upgrading and reset the
settings.

**Comment by Dtwpurple** [comment]
I tried deleting the setting and reinstalling but it doesn’t work on my 6s. Only 1.3 works.

**Comment by LacertosusRepo** [comment]
Strange! Ill link an experimental build i have going right now, see if that fixes your issue. Im
 guessing its something wrong on my end, not XenInfo. [Here is the download](https://mega.nz/#!WVABCaKK!ePXAG9v9gsHcek4xbCNJEbIjDimVroyBrPdv7-iF5JQ).

**Comment by LacertosusRepo** [comment]
Issue was my preferences! Not XenHTML. Should be fixed in version 1.5.
