### ISSUE TITLE
[BUG] Libellum

### ISSUE THREAD

**Issue by rpelich123** [LacertosusRepo/LacertosusRepo.github.io#60]
#### **Information:**
- *Device:* 11 pro max
- *iOS:* 14.1
- *Tweak:* libellum
- *Package Version:* newest

#### **Describe the bug:**

when bolding text, it works when typing it, however when u click 'done' it comes back to non bold. i tried selecting it and bolding it but same problem

#### **To Reproduce:**
If possible, describe how to reproduce the error.

#### **Expected behavior:**
when u bold or type bold and click 'done' it should stay bold

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by LacertosusRepo** [comment]
This has been fixed for the next update.
