### ISSUE TITLE
Imperium - 1.4 breaks gestures

### ISSUE THREAD

**Issue by guy4jesuschrist** [LacertosusRepo/LacertosusRepo.github.io#7]
After upgrading from 1.3 to 1.4, I&apos;m no longer able to use gestures on the NC music notification or CC music module to control my music. I use Google Play Music, so I'm guessing the changes you made to incorporate the gestures into Apple Music, broke this capability.

**Comment by LacertosusRepo** [comment]
Thanks for reporting! Im pretty sure I already know what the bug is, try reselecting all your options in preferences.

**Comment by LacertosusRepo** [comment]
Should be fixed in 1.5
