### ISSUE TITLE
[BUG] NowPlayingIcon not working on iOS 14.5

### ISSUE THREAD

**Issue by siddiqq** [LacertosusRepo/LacertosusRepo.github.io#70]
#### **Information:**
- *Device:* 7+
- *iOS:* 14.5
- *Tweak:* NowPlayingIcon
- *Package Version:*Latest

#### **Describe the bug:**
Hello :) Can you please update this tweak to work with iOS 14.5? Thank you

#### **To Reproduce:**
If possible, describe how to reproduce the error.

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by LacertosusRepo** [comment]
Update v1.3.2 Adds support for iOS 14.5.
