### ISSUE TITLE
[REQUEST] Speculum - Literals in “Date label format”

### ISSUE THREAD

**Issue by k1nzu** [LacertosusRepo/LacertosusRepo.github.io#72]
#### **Is your feature request related to a problem? Please describe.**

I would like an option for using literals in the “date label format”. Example: here in Brazil a full date format would look  like “sábado, 19 de junho” or, in english, “saturday, 19 of june”.

I tried using the word “de” (of) in single and double quotes, but it keeps getting translated to NSDateFormat.

#### **Describe the solution you'd like**
When enclosed in single or double quotes, the formatting specifier should not be evaluated according to NSDateFormat. 

#### **Describe alternatives you've considered**
None. 
#### **Additional context**
Idea of date label format in use:

![image](https://user-images.githubusercontent.com/39500406/122654926-f71f8d00-d124-11eb-94a9-ef2c64292215.jpeg)

**Comment by LacertosusRepo** [comment]
As is says in Speculum's description, the package is no longer being supported. Therefore this feature will no be added.
