### ISSUE TITLE
[BUG] Speculum - Overlapping battery indicator on LS

### ISSUE THREAD

**Issue by k1nzu** [LacertosusRepo/LacertosusRepo.github.io#73]
#### **Information:**
- *Device:* iPhone XS
- *iOS:* 14.3
- *Tweak:* Speculum
- *Package Version:* 1.3.5

#### **Describe the bug:**
The battery indicator on LockScreen overlaps Speculum when the device is connected to the charger. 
#### **To Reproduce:**
Go to the LockScreen and connect the device to the charger.

#### **Expected behavior:**
The stock battery indicator should be hidden when Speculum is enabled. Also, it would be nice to get the localized string from the same indicator. 

#### **Screenshots:**
https://user-images.githubusercontent.com/39500406/122655858-461cf080-d12c-11eb-958b-34c5960fde6d.MOV

#### **Additional context**
None

**Comment by LacertosusRepo** [comment]
As is says in Speculum's description, the package is no longer being supported. Therefore this bug will not be fixed.
