### ISSUE TITLE
Allow downgrading tweaks?

### ISSUE THREAD

**Issue by rastafaa** [LacertosusRepo/LacertosusRepo.github.io#77]
I love your AddtoFavorites spotify tweak.. but the newest 1.1 doesn't work with older version of spotify that I'm using (crashes), any chance you can provide the older tweak versions which worked on the older spotify? Usually I save multiple versions but I'm not finding older for this tweak.  Thanks!

**Comment by LacertosusRepo** [comment]
The tweak is only maintained for the latest version of Spotify and unfortunately I do not keep any backups of older versions of the tweak.
