### ISSUE TITLE
Anything past 1.3 breaks the media player controls

### ISSUE THREAD

**Issue by Dtwpurple** [LacertosusRepo/LacertosusRepo.github.io#8]
## *For the title, follow this example: Tweak - Short Bug Description*

------------------
**Tweak/Theme:**
**Version:**
**Device:**
**iOS Version:**

-----------------
**Issue/Bug:**

-------------------------
**Additional Comments:**
I tried resetting the settings and nothing seems to work. Only 1.3 seems to work correctly

**Comment by LacertosusRepo** [comment]
I am not able to reproduce this bug anymore. Version 1.6/1.7 should work for all. Make sure to include your device and iOS version next time.

**Comment by Dtwpurple** [comment]
It’s a 6s on 11.3.1 . I’m using glacier maybe that’s it. I don’t need the new features so I’ll jut not update anymore

**Comment by Dtwpurple** [comment]
It works on 1.3 tho. Well have a good one (:
