### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ycodryn** [LacertosusRepo/LacertosusRepo.github.io#9]
## *For the title, follow this example: Tweak - Short Bug Description*

------------------
**Tweak/Theme:  Vitrum
**Version: 1.0
**Device: Ipad Pro
**iOS Version: 11.3.1

-----------------
**Issue/Bug: Tweak is installing, but in preference I see Glacies not Vitrum and I see an error, something like glacies preference loader not working.

-------------------------
**Additional Comments:**

**Comment by LacertosusRepo** [comment]
Please try the upcoming update of v1.1, Packix has yet to approve it. But once its available, try it and tell me if it starts working. It may be an incompatibility with iPads.

**Comment by LacertosusRepo** [comment]
Marking fixed since no further commenting.
